language: python

python:
- "3.5"

services:
  - postgresql

env:
  - TOXENV=django111
  - TOXENV=django20
  - TOXENV=django21
  - TOXENV=django22

before_install:
  - export DJANGO_SETTINGS_MODULE=openedxstats.settings.testing

before_script:
  - pip install -r requirements/travis.txt

cache:
  - pip

script:
  - make tests
